#!/bin/sh
source ./env_localization.sh
set -e

FLUTTER_LOCALIZATION_PATH="${LOCALIZATION_PACKAGE_PATH}"
node gen.js $EXCEL_LOCALIZATION_FILE_PATH $FLUTTER_LOCALIZATION_PATH
cd $PROJECT_PATH
flutter gen-l10n