#!/bin/sh
set -e
FLUTTER_LOCALE_GENERATE_PATH=[Your folder git repo]
EXCEL_LOCALIZATION_FILE_PATH=[example.xlsx]
LOCALIZATION_PACKAGE_PATH=[example/lib/src/localization/]
PROJECT_PATH=[example]

cd $FLUTTER_LOCALE_GENERATE_PATH
node gen.js $EXCEL_LOCALIZATION_FILE_PATH $LOCALIZATION_PACKAGE_PATH
cd $PROJECT_PATH
flutter gen-l10n